# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Maria Izzi
email: izzimaria.mi@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Maria Izzi's Portfolio, made using Jekyll
baseurl: "" # the subpath of your site, e.g. /blog
url: "maria-izzi.github.io" # the base hostname & protocol for your site\
github_username:  maria-izzi

# Build settings
markdown: kramdown
